def use_module(bld):
    sources = bld.path.ant_glob('src/*.c')
    bld.env.MODULE_XCC_FLAGS = bld.env.XCC_FLAGS = ['-Os']
    bld.module(
        source=sources,
        includes='api',
        optional_headers='debug_conf.h',
        version='2.1.0')
