def configure(conf):
    conf.load('xwaf.compiler_xcc')


def build(bld):
    bld.env.TARGET_ARCH = 'SLICEKIT-L16'
    bld.env.XCC_FLAGS = ['-DDEBUG_PRINT_ENABLE=1']

    # Build our program
    prog = bld.program(
        source='src/main.xc',
        depends_on='lib_logging')
